language: ruby
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.mongoid2
    - rvm: 1.9.3
      gemfile: Gemfile
branches:
  only:
    - master
services:
  - mongodb
notifications:
  disabled: true
before_script:
  - rake test:prepare
